const productos = [
    {
        id: 1,
        nombre: "Mate",
        precio: 20,
        imagen: './public/imagenes/mate.JPG',
        cantidad: 1,
    },
    {
        id: 2,
        nombre: "Bombilla",
        precio: 10,
        imagen: './public/imagenes/bombilla.JPG',
        cantidad: 1,
    },
    {
        id: 3,
        nombre: "Yerba Amanda 1kg",
        precio: 12,
        imagen: './public/imagenes/amanda.JPG',
        cantidad: 1,
    },
    {
        id: 4,
        nombre: "Yerba Playadito 1kg",
        precio: 12,
        imagen: './public/imagenes/playadito1kg.JPG',
        cantidad: 1,
    },
    {
        id: 5,
        nombre: "Yerba Amanda 500grs",
        precio: 7,
        imagen: './public/imagenes/amanda.JPG',
        cantidad: 1,
    },
    {
        id: 6,
        nombre: "Yerba Playadito 500grs",
        precio: 7,
        imagen: './public/imagenes/playadito500.JPG',
        cantidad: 1,
    },
    {
        id: 7,
        nombre: "Alfajores 6 unidades",
        precio: 14,
        imagen: './public/imagenes/alfajores.JPG',
        cantidad: 1,
    },
    {
        id: 8,
        nombre: "Alfajores 12 unidades",
        precio: 25,
        imagen: './public/imagenes/alfajores.JPG',
        cantidad: 1,
    },
];